version: "3.9"
services:
  tcp:
    image: 366328713202.dkr.ecr.us-east-1.amazonaws.com/ecs-network-perf/tcp
    build:
      context: .
      dockerfile: tcp.Dockerfile

  tcp_nginx:
    # Need to build the image to include our config for Copilit sidecar usage
    image: 366328713202.dkr.ecr.us-east-1.amazonaws.com/ecs-network-perf/tcp:nginx
    build:
      context: .
      dockerfile: tcp/nginx.Dockerfile
    environment:
      - "APP_HOST=tcp"
    ports:
      - "8080:80"
    depends_on:
      - "tcp"

  combined:
    build:
      context: .
      dockerfile: combined.Dockerfile
    ports:
      - "8081:80"
