# Read the README.md for descriptions of the services and the choices made here
version: "3.9"
services:
  tcp:
    image: ${COPILOT_AWS_ACCOUNT_ID}.dkr.ecr.${COPILOT_AWS_REGION}.amazonaws.com/ecs-network-perf/tcp
    build:
      context: .
      dockerfile: tcp.Dockerfile

  tcp_nginx:
    image: ${COPILOT_AWS_ACCOUNT_ID}.dkr.ecr.${COPILOT_AWS_REGION}.amazonaws.com/ecs-network-perf/tcp:nginx
    build:
      context: .
      dockerfile: tcp/nginx.Dockerfile
    environment:
      - "APP_HOST=tcp"
    ports:
      - "8080:80"
    depends_on:
      - "tcp"

  combined:
    image: ${COPILOT_AWS_ACCOUNT_ID}.dkr.ecr.${COPILOT_AWS_REGION}.amazonaws.com/ecs-network-perf/combined
    build:
      context: .
      dockerfile: combined.Dockerfile
    ports:
      - "8081:80"

  sharedvol:
    image: ${COPILOT_AWS_ACCOUNT_ID}.dkr.ecr.${COPILOT_AWS_REGION}.amazonaws.com/ecs-network-perf/sharedvol
    build:
      context: .
      dockerfile: sharedvol.Dockerfile
    volumes:
      - sharedvol_tmp:/tmp

  sharedvol_nginx:
    image: ${COPILOT_AWS_ACCOUNT_ID}.dkr.ecr.${COPILOT_AWS_REGION}.amazonaws.com/ecs-network-perf/sharedvol:nginx
    build:
      context: .
      dockerfile: sharedvol/nginx.Dockerfile
    ports:
      - "8082:80"
    volumes:
      - sharedvol_tmp:/tmp
    depends_on:
      - "sharedvol"

volumes:
  sharedvol_tmp:
